apiVersion: v1
kind: Namespace
metadata:
  name: app1
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app1
  namespace: app1
spec:
  interval: 1m
  path: "./manifests"
  sourceRef:
    kind: GitRepository
    name: example-repo
  prune: true
