apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tryrocket-cloud
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  commonName: tryrocket.cloud
  dnsNames:
  - tryrocket.cloud
  - nginx.tryrocket.cloud
  - nginx1.tryrocket.cloud
  - nginx2.tryrocket.cloud
